#!/bin/sh
#SBATCH --job-name=all_wiki_gate
#SBATCH --mail-type=END
#SBATCH --mail-user=adel.ghamnia@irit.fr
#SBATCH --cpus-per-task=32
#SBATCH --nodes=6
#SBATCH --output=log.out
#SBATCH --error=error.log


JAVA=/logiciels/java1.8/bin/java
GATE=/users/melodi/aghamnia/gate-8.1-build5169-BIN
DIR=/users/melodi/aghamnia/TextToBabelNet/wiki_gate

$JAVA -Xmx512g -jar TextToBabelNetValidation.jar -parse $DIR